# Advanced Multi-Mission Operations System (AMMOS) Instrument Toolkit (AIT)
# Bespoke Link to Instruments and Small Satellites (BLISS)
#
# Copyright 2018, by the California Institute of Technology. ALL RIGHTS
# RESERVED. United States Government Sponsorship acknowledged. Any
# commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
#
# This software may be subject to U.S. export control laws. By accepting
# this software, the user agrees to comply with all applicable U.S. export
# laws and regulations. User has the responsibility to obtain export licenses,
# or other export authority as may be required before exporting such
# information to foreign countries or providing access to foreign persons.

from enum import Enum

class Event(Enum):
    # USER
    E30_RECEIVED_PUT_REQUEST = "E30_RECEIVED_PUT_REQUEST"
    E31_RECEIVED_SUSPEND_REQUEST = "E31_RECEIVED_SUSPEND_REQUEST"
    E32_RECEIVED_RESUME_REQUEST = "E32_RECEIVED_RESUME_REQUEST"
    E33_RECEIVED_CANCEL_REQUEST = "E33_RECEIVED_CANCEL_REQUEST"
    E34_RECEIVED_REPORT_REQUEST = "E34_RECEIVED_REPORT_REQUEST"
    E40_RECEIVED_FREEZE_REQUEST = "E40_RECEIVED_FREEZE_REQUEST"
    E41_RECEIVED_THAW_REQUEST = "E41_RECEIVED_THAW_REQUEST"

    # Other events
    E2_ABANDON_TRANSACTION = "E2_ABANDON_TRANSACTION"
    E3_NOTICE_OF_CANCELLATION = "E3_NOTICE_OF_CANCELLATION"
    E4_NOTICE_OF_SUSPENSION = "E4_NOTICE_OF_SUSPENSION"
    E5_SUSPEND_TIMERS = "E5_SUSPEND_TIMERS"
    E6_RESUME_TIMERS = "E6_RESUME_TIMERS"

    # ENTITY
    E10_RECEIVED_METADATA_PDU = "E10_RECEIVED_METADATA_PDU"
    E11_RECEIVED_FILEDATA_PDU = "E11_RECEIVED_FILEDATA_PDU"
    E12_RECEIVED_EOF_NO_ERROR_PDU = "E12_RECEIVED_EOF_NO_ERROR_PDU"
    E13_RECEIVED_EOF_CANCEL_PDU = "E13_RECEIVED_EOF_CANCEL_PDU"
    E14_RECEIVED_ACK_EOF_NO_ERROR_PDU = "E14_RECEIVED_ACK_EOF_NO_ERROR_PDU"
    E14_RECEIVED_ACK_EOF_CANCEL_PDU = "E14_RECEIVED_ACK_EOF_CANCEL_PDU"
    E15_RECEIVED_NAK_PDU = "E15_RECEIVED_NAK_PDU"
    E16_RECEIVED_FINISHED_NO_ERROR_PDU = "E16_RECEIVED_FINISHED_NO_ERROR_PDU"
    E17_RECEIVED_FINISHED_CANCEL_PDU = "E17_RECEIVED_FINISHED_CANCEL_PDU"
    E18_RECEIVED_ACK_FIN_NO_ERROR_PDU = "E18_RECEIVED_ACK_FIN_NO_ERROR_PDU"
    E18_RECEIVED_ACK_FIN_CANCEL_PDU = "E18_RECEIVED_ACK_FIN_CANCEL_PDU"

    E0_SEND_FILE_DIRECTIVE = "E0_SEND_FILE_DIRECTIVE"
    E1_SEND_FILE_DATA = "E1_SEND_FILE_DATA"

    # TIMER
    E25_ACK_TIMER_EXPIRED = "E25_ACK_TIMER_EXPIRED"
    E26_NAK_TIMER_EXPIRED = "E26_NAK_TIMER_EXPIRED"
    E27_INACTIVITY_TIMER_EXPIRED = "E27_INACTIVITY_TIMER_EXPIRED"
