from enum import Enum

class Event(Enum):
    # USER
    RECEIVED_PUT_REQUEST = "RECEIVED_PUT_REQUEST"
    RECEIVED_SUSPEND_REQUEST = "RECEIVED_SUSPEND_REQUEST"
    RECEIVED_RESUME_REQUEST = "RECEIVED_RESUME_REQUEST"
    RECEIVED_CANCEL_REQUEST = "RECEIVED_CANCEL_REQUEST"
    RECEIVED_ABANDONED_REQUEST = "RECEIVED_ABANDONED_REQUEST"
    RECEIVED_REPORT_REQUEST = "RECEIVED_REPORT_REQUEST"
    RECEIVED_FREEZE_REQUEST = "RECEIVED_FREEZE_REQUEST"
    RECEIVED_THAW_REQUEST = "RECEIVED_THAW_REQUEST"

    # ENTITY
    RECEIVED_METADATA_PDU = "RECEIVED_METADATA_PDU"
    RECEIVED_FILEDATA_PDU = "RECEIVED_FILEDATA_PDU"
    RECEIVED_EOF_NO_ERROR_PDU = "RECEIVED_EOF_NO_ERROR_PDU"
    RECEIVED_ACK_EOF_NO_ERROR_PDU = "RECEIVED_ACK_EOF_NO_ERROR_PDU"
    RECEIVED_EOF_CANCEL_PDU = "RECEIVED_EOF_CANCEL_PDU"
    RECEIVED_ACK_EOF_CANCEL_PDU = "RECEIVED_ACK_EOF_CANCEL_PDU"
    RECEIVED_NAK_PDU = "RECEIVED_NAK_PDU"
    RECEIVED_FINISHED_NO_ERROR_PDU = "RECEIVED_FINISHED_NO_ERROR_PDU"
    RECEIVED_ACK_FIN_NO_ERROR_PDU = "RECEIVED_ACK_FIN_NO_ERROR_PDU"
    RECEIVED_FINISHED_CANCEL_PDU = "RECEIVED_FINISHED_CANCEL_PDU"
    RECEIVED_ACK_FIN_CANCEL_PDU = "RECEIVED_ACK_FIN_CANCEL_PDU"

    SEND_FILE_DIRECTIVE = "SEND_FILE_DIRECTIVE"
    SEND_FILE_DATA = "SEND_FILE_DATA"

    # TIMER
    ACK_TIMER_EXPIRED = "ACK_TIMER_EXPIRED"
    NAK_TIMER_EXPIRED = "NAK_TIMER_EXPIRED"
    INACTIVITY_TIMER_EXPIRED = "INACTIVITY_TIMER_EXPIRED"