language: python
python:
  - "3.10"

branches:
  only:
    - master

env:
    - AIT_CONFIG: ${TRAVIS_BUILD_DIR}/config/config.yaml

install:
  - pip install .[tests]

script: pytest --ignore ait/dsn/bin/examples --cov=ait
